# Generated by Django 3.2.15 on 2022-09-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='update',
            new_name='updated_at',
        ),
    ]
